version: '2'
services:
    odata:
        build: ./odata
        ports:
            - 5000:5000
        depends_on:
            - db
        links:
            - db
        environment:
            DATABASE_URL: "postgres://nfldb:nfldb@db/nfldb"
    nfldb-update:
        build: ./nfldb-update
        depends_on:
            - db
        links:
            - db
    db:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: nfldb
            POSTGRES_USER: nfldb
