version: '2'
services:
    odata:
        build: ./odata
        ports:
            - 80:80
            - 443:443
        depends_on:
            - db
        links:
            - db
    # nfldb:
    #     build: ./nfldb
    #     depends_on:
    #         - db
    #     links:
    #         - db
    db:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: nfldb
            POSTGRES_USER: nfldb
